spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_sales
    driverClassName: org.postgresql.Driver
    username: ticket_sales
    password: ticket_sales
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id

topic:
  name:
    producer: ticket-sales

auto:
  create:
    topics:
      enable: true